#!/usr/bin/bash

export CLICOLOR=true

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	    . "$HOME/.bashrc"
    fi
fi

if [ -e $HOME/.bash_aliases ] ; then
    . $HOME/.bash_aliases
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [[ ! -v ANDROID_HOME ]]; then
    export ANDROID_HOME=$HOME/.local/android
fi

export PATH=$HOME/.cargo/bin:$PATH
export PATH=$PATH:$ANDROID_HOME/tools/emulator
export PATH=$PATH:$ANDROID_HOME/tools/bin
