#!/usr/bin/bash

export CLICOLOR=true

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	    . "$HOME/.bashrc"
    fi
fi

if [ -e $HOME/.bash_aliases ] ; then
    . $HOME/.bash_aliases
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

function map_tablet {
    xsetwacom --list devices
    read -p "Type in pen id: " id
    xrandr -q
    read -p "Display to map to: " ans
    xsetwacom set $id MapToOutput $ans
}

export PATH="$HOME/.cargo/bin:$PATH"
