#!/usr/bin/env bash

export DOTFILE_ROOT=~/.mine_dotfiles
export ALIAS_ROOT=$DOTFILE_ROOT/bash_aliases
export PROFILE_ROOT=$DOTFILE_ROOT/bash_profile

# This needs to be called first
. $PROFILE_ROOT/scripts/start

for f in $PROFILE_ROOT/scripts/*; do
  if [[ -f "$f" ]]; then
    . "$f"
  fi
done

if [[ ! $(uname -v) =~ Microsoft && -f ~/.local/bin/virtualenvwrapper.sh ]]; then
  . ~/.local/bin/virtualenvwrapper.sh >/dev/null

  pip3 completion --bash >/dev/null
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
