#!/usr/bin/bash
# Path exports for Android Studio to work

OS=$(uname -s)
case $OS in
    [lL]inux* )
        export ANDROID_HOME=$HOME/Android/Sdk
        ;;
    [dD]arwin* )
        export ANDROID_HOME=$HOME/Library/Android
        ;;
esac

export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/tools/bin