#!/usr/bin/env bash
# Source NVM
if [[ -f '.nvmrc' ]]; then
    echo -e "${LG}.nvmrc found. Calling nvm use...${NC}"
    if [[ -z `command -v nvm` ]]; then
        if [[ -d ~/.nvm ]]; then
            export NVM_DIR="$HOME/.nvm"
            . ~/.nvm/nvm.sh
            . ~/.nvm/bash_completion
            nvm use
            cls
        else
            echo "NVM directory not found. Do you have it installed?"
        fi
    else
        nvm use
        cls
    fi
fi

# Update NVM
function update_nvm() {
    (
        cd "$NVM_DIR"
        git fetch --tags origin
        co `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
    ) && \. "$NVM_DIR/nvm.sh"
}
