#!/usr/bin/bash
# Source NVM
if [[ -z `command -v nvm` ]]; then
    if [[ -d ~/.nvm ]]; then
        export NVM_DIR="$HOME/.nvm"
        . ~/.nvm/nvm.sh
        . ~/.nvm/bash_completion
    else
        echo "NVM directory not found. Do you have it installed?"
    fi
fi
