#!/usr/bin/bash
# Git aliases
alias acip='add && cip'
alias add='git add .'
alias br="git branch"
alias brv="git branch -vv"
alias ci="git commit"
alias cl="git add CHANGELOG.md && ci -nm 'Add Changelog Entry'"
alias git_current_branch='git rev-parse --abbrev-ref HEAD'
alias git_remote_branch='git rev-parse --abbrev-ref --symbolic-full-name @{u}'
alias grep_all="br -a | tr -d \* | sed '/->/d' | xargs git grep"
alias lg="git log --graph --pretty=format:'%C(red)%h%Cgreen%d%Creset %s %C(blue) %an, %ar%Creset'"
alias mg="git merge"
alias mgd="mg develop"
alias prune='git fetch origin && git remote prune origin && begone_thots'
alias ss='git status -sb'

# Git functions
function bdm() {
    read -p "Deletes all branches that have been merged with master & develop. Proceed? [Y/n]" ans
    if [[ $ans =~ "[yY]" ]] || [[ -z $ans ]]; then
        git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d
        echo "Complete!"
    else
        echo "Aborting..."
    fi
}

# Delete local branches which remotes have been deleted
function begone_thots() {
    git branch -v \
    | grep -E '\[gone\]' \
    | cut -c 3- \
    | perl -lane 'print m/^[-\w\/\.]+?\s/g' \
    | xargs git branch -D \
    && no_cls $1
}

function co() {
    if [ $# -eq 0 ]; then
        case $(uname -s) in
            [lL]inux* )
                git checkout $(git branch | pick)
            ;;
            [dD]arwin* )
                git checkout $(git branch | fzf)
            ;;
        esac
    else
        git checkout "$@"
    fi
}

# Shorthand to checkout to a new branch from another
function cob() {
    if [[ -z "$1" ]]; then
        echo "Please specify a new branch name."
    else
        if [[ -z "$2" ]]; then
            co develop && co -b $1
        else
            co $2 && co -b $1
        fi
    fi
}

function del() {
    local current_branch=$(git_current_branch)
    if ! [[ $current_branch =~ (master|develop) ]]; then
        dev -s && br -D $current_branch
    else
        echo -e "${LR}Currently on $current_branch. Not deleting this.${NC}"
    fi
}

function dev() {
    if ! [[ "$1" =~ ^- ]]; then
        co develop && tug
        if [[ -z "$1" ]]; then
            co - && git merge develop
        else
            # Check if it's a remote branch
            git rev-parse --verify origin/$1 &>/dev/null
            if [[ $? != 0 ]]; then
                # Check if it's a new branch
                git rev-parse --verify $1 &>/dev/null
                if [[ $? != 0 ]]; then
                    echo -e "${BY}New branch $1 specified. Creating new branch...${NC}"
                    co -b $1
                fi
            else
              co $1 && git merge develop
            fi
        fi
    else
        case $1 in
            "-s")
                co develop && tug && no_cls $2
                ;;
            "-d")
                del
                ;;
            "-r")
                local branch=$(git_current_branch)
                co develop && tug && br -D $branch && co -b $branch
                ;;
            "-h")
                echo "$0 {-h|-s|-d|-r}"
                echo "-h: Displays this"
                echo "-s: Checks out to dev, pulls, and stays in dev"
                echo "-d: Does what -s does and deletes the previous branch"
                echo "-r: Does what -r does, then recreates and checks out to the previous branch"
                ;;
            *)
                echo "Undefined command $1"
                dev -h
                ;;
        esac
    fi
}

function git_relative_remote_branch() {
    git rev-parse --abbrev-ref --symbolic-full-name @{u} \
    | perl -lane "print m/^$(git remote)\/(.+?)$/" \
    | xargs echo
}

function nuke_all_local_branches() {
    case $1 in
        "-h")
            echo "$0 [-h|-r]:"
            echo "-h: Display this help screen"
            echo "-r: Retain current branch"
            ;;
        "-r" | *)
            if [[ "$1" == "-r" ]]; then
                minefy
            fi
            dev -s && git remote prune origin && br | cut -c 3- | awk '!/^develop|mine/ {print $1}' | xargs git branch -D
            if [[ "$1" == "-r" ]]; then
                co - && minefy
            fi
            ;;
    esac
}

function tug() {
    local remote=$(git_relative_remote_branch)
    if [[ $? == 0 ]]; then
        git fetch origin && git rebase --rebase-merges origin/$remote
    else
        echo -e "${BY}As the sign says bud; we can't pull.${NC}"
    fi
}

function discharge() {
    if [[ $(git_current_branch) == "develop" ]]; then
        echo -e "${BR}You're currently on develop. We ain't pushin'.${NC}"
    else
        git_remote_branch &>/dev/null
        if [[ $? != 0 ]]; then
            git push -u origin $(git_current_branch) && no_cls $1
        else
            git push && no_cls $1
        fi
    fi
}

function minefy() {
    if [[ $1 =~ "-h" ]]; then
        echo "Toggles between adding/removing 'mine/' from the start of the branch name"
    else
        if [[ -z $1 ]]; then
            local current_branch=$(git_current_branch)
            if [[ $current_branch =~ "mine/" ]]; then
                echo $current_branch | cut -c 6- | xargs git branch -m
            else
                br -m "mine/${current_branch}"
            fi
            echo -e "${LG}Current branch name is $(git_current_branch) ${NC}"
        fi
    fi
}
