#!/usr/bin/bash
# IB aliases
# This is for work at Radweb. Once I'm outta this place then just delete this
alias ib='cd ~/Documents/Work/InventoryBase && nvm use && clear && printf "\e[3J"'
alias ibr='cd ~/Documents/Work/InventoryBase-Go-RN && nvm use && rvm use && clear && printf "\e[3J"'

# Opens the debugging menu on the test Android phone
alias debug_android_menu="adb shell input keyevent 82 && cls"
alias debug_android_start="react-native run-android --deviceId D1AGAS3780905879 && cls"
alias debug_android_reverse="adb -s D1AGAS3780905879 reverse tcp:8081 tcp:8081 && cls"

function yarn_it_all() {
    nvm use
    clear && printf "\e[3J"
    yarn flow && yarn lint:fix && yarn test
}
