#!/usr/bin/bash
# IB aliases
# This is for work at Radweb. Once I'm outta this place then just delete this
alias ib='cd_and_nvm ~/Documents/Work/InventoryBase'
alias ibr='cd_and_nvm ~/Documents/Work/InventoryBase-Go-RN && rvm use && cls'
alias ni='cd_and_nvm ~/Documents/Work/NicheCom-Mobile'

# Opens the debugging menu on the test Android phone
alias debug_android_menu="adb shell input keyevent 82 && cls"
alias debug_android_start="react-native run-android --deviceId D1AGAS3780905879 && cls"
alias debug_android_reverse="adb -s D1AGAS3780905879 reverse tcp:8081 tcp:8081 && cls"

function yarn_it_all {
    nvm use
    clear && printf "\e[3J"
    yarn flow && yarn lint:fix | grep error -B 2 && yarn test
}

function cd_and_nvm {
    if [[ $1 != $(pwd) ]]; then
        cd $1
    fi

    if [[ ! -f .nvmrc ]]; then
        echo -e "${LY}No .nvmrc in this folder?${NC}"
        return
    fi

    local nvm_version=$(cat .nvmrc)
    local depth=$(grep -o '\.' <<< $nvm_version | wc -l)
    local current_node_version=$(node -v)
    current_node_version=${current_node_version#v}

    if [[ $nvm_version != $current_node_version ]]; then
        if [[ $depth =~ "2" ]]; then
            nvm use
        elif [[ $depth =~ "1" ]]; then
            current_node_version_no_patch=${current_node_version%.*}

            if [[ $nvm_version != $current_node_version_no_patch ]]; then
                nvm use
            fi
        fi
        clear && printf "\e[3J"
    else
        echo -e "${BLY}Couldn't call NVM?${NC}"
    fi
}