#!/usr/bin/bash
function install_node() {
    local path=$(pwd)
    if [[ $path =~ InventoryBase-Go-RN$ ]]; then
        yarn
    else
        npm i
    fi
}

function install_pods() {
    local path=$(pwd)
    if [[ $path =~ InventoryBase-Go-RN$ ]]; then
        echo -e "${LY}Nuking Pods...${NC}"
        cd ios && rvm use && rm -rf Pods/ && pod install
        cd - &> /dev/null
    fi
}

function nuke_node() {
    local path=$(pwd)

    echo -e "${LG}You're here: $original_path${NC}"

    while [[ ! -f $path/package.json ]]; do
        if [[ ! $path =~ ^$HOME/Documents ]]; then
            echo -e "${LR}No `package.json` found in this project. Aborting.${NC}"
            return
        fi
        path=${path%/*}
    done

    cd $path

    if ! [[ -d node_modules ]]; then
        read -p "No node_modules. Install packages anyway? [yN] " ans
        if [[ ! $ans =~ ^[yY]$ ]]; then
            echo -e "${LY}y wasn't received. Not installing.${NC}"
            cd $original_path
            return
        else
            install_node
            cd - &> /dev/null
            return
        fi
    fi

    read -p "You sure you want to nuke node_modules? [y/N] " ans
    if [[ $ans =~ ^[yY]$ ]]; then
        rm -rf node_modules
        install_node
        install_pods
    elif [[ -z $ans ]]; then
        echo 'N received. Not nuking.'
    else
        echo "$ans received. Not nuking."
    fi
    cd - &> /dev/null
}
