#!/usr/bin/env bash

export DOTFILE_ROOT=~/.mine_dotfiles
export ALIAS_ROOT=$DOTFILE_ROOT/aliases
export PROFILE_ROOT=$DOTFILE_ROOT/profile

ori=$(pwd)
cd $PROFILE_ROOT/scripts

# This needs to be called first
. ./start

for f in *; do
  if [[ -f "$f" && ! "$f" =~ start ]]; then
    . "./$f"
  fi
done

cd $ori

if [[ ! $(uname -v) =~ Microsoft && -f ~/.local/bin/virtualenvwrapper.sh ]]; then
  . ~/.local/bin/virtualenvwrapper.sh >/dev/null

  pip3 completion --bash >/dev/null
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
