#!/usr/bin/env bash

export DOTFILE_ROOT=~/.mine_dotfiles
PROFILE_ROOT=$DOTFILE_ROOT/profile
export ALIAS_ROOT=$DOTFILE_ROOT/aliases

. $PROFILE_ROOT/scripts/start

# Source NVM
. $PROFILE_ROOT/scripts/nvm

# IB scripts
. $PROFILE_ROOT/scripts/ib

# Source RVM
. $PROFILE_ROOT/scripts/rvm

# Source no_cls
. $PROFILE_ROOT/scripts/no_cls

# Export paths
. $PROFILE_ROOT/scripts/path_exports

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
