#!/usr/bin/env bash
# Initial stuff. Gotta have em here at the start.
alias mine="cd $DOTFILE_ROOT"

# Important. Never delete.
alias please='sudo '

# Source aliases
for f in $ALIAS_ROOT/alias_functions/*; do
    . "$f"
done
