#!/usr/bin/env bash
# Initial stuff. Gotta have em here at the start.
alias mine="cd $DOTFILE_ROOT"

# Important. Never delete.
alias please='sudo '

# Source aliases
cd $ALIAS_ROOT/alias_functions
for f in *; do
    . "./$f"
done
cd ~ &> /dev/null
