#!/usr/bin/env bash
function fuckin_pen() {
    id=$(xsetwacom --list devices | perl -nle 'print $1 if /id: (\d{2})\s+type: STYLUS/')
    xsetwacom set $id MapToOutput 'DVI-D-0'
    no_cls $1
}

alias mkvirtualenv='mkvirtualenv --no-site-packages --distribute'
