#!/usr/bin/env bash
# These are scripts that both machines have to run at the start

export CLICOLOR=true

# Load Aliases
if [[ -e $ALIAS_ROOT/aliases ]]; then
    . $ALIAS_ROOT/aliases
fi

# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/.local/bin" && $PATH != *$HOME/.local/bin* ]] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
