#!/usr/bin/env bash
# Path exports for Android Studio to work

OS=$(uname -s)
case $OS in
    [lL]inux* )
        ANDROID_HOME=$HOME/Android/Sdk
        ;;
    [dD]arwin* )
        ANDROID_HOME=$HOME/Library/Android
        export ANDROID_SDK_ROOT=~/Library/Android/sdk
        export ANDROID_AVD_HOME=~/.android/avd
        ;;
esac

if [[ $PATH != *$ANDROID_HOME/emulator* ]]; then
    export PATH=$PATH:$ANDROID_HOME/emulator
fi

if [[ $PATH != *$ANDROID_SDK_ROOT/tools/bin* ]]; then
    export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
fi

if [[ $PATH != *$ANDROID_HOME/platform-tools* ]]; then
    export PATH=$PATH:$ANDROID_HOME/platform-tools
fi

