#!/usr/bin/env bash
# Path export for CLI-only Android Studio

if [[ ! `uname -s` =~ "[lL]inux" ]]; then
    return
fi

export ANDROID_HOME=~/.local/android-studio/sdk

. ../../utils/addToPath.sh $ANDROID_HOME/emulator
. ../../utils/addToPath.sh $ANDROID_HOME/tools
. ../../utils/addToPath.sh $ANDROID_HOME/tools/bin
. ../../utils/addToPath.sh $ANDROID_HOME/platform-tools
. ../../utils/addToPath.sh $HOME/.local/android-studio/cmdline-tools/bin
