#!/usr/bin/env bash
# Path export for CLI-only Android Studio

if [[ ! `uname -s` =~ "[lL]inux" ]]; then
    return
fi

if [[ $PATH != "*/home/shep/.local/android-studio/cmdline-tools/bin*" ]]; then
    export PATH=$PATH:~/.local/android-studio/cmdline-tools/bin
fi
