#!/usr/bin/env bash
# Path exports for Android Studio to work

if [[ -z `command -v android-studio` ]]; then
    return
fi

OS=$(uname -s)
case $OS in
    [lL]inux* )
        ANDROID_HOME=$HOME/Android/Sdk
        ;;
    [dD]arwin* )
        ANDROID_HOME=$HOME/Library/Android
        export ANDROID_SDK_ROOT=~/Library/Android/sdk
        export ANDROID_AVD_HOME=~/.android/avd
        if [[ $PATH != *$ANDROID_SDK_ROOT/tools/bin* ]]; then
            export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
        fi
        ;;
esac

. ../../utils/addToPath.sh $ANDROID_HOME/emulator
. ../../utils/addToPath.sh $ANDROID_HOME/platform-tools
