#!/usr/bin/env bash
# Path export for Ruby Gems

if [[ ! `command -v gem` ]]; then
    return
fi

. ../../utils/addToPath.sh $HOME/gems/bin

if [[ -z "$GEM_HOME" ]]; then
    # Install Ruby Gems to ~/gems
    export GEM_HOME="$HOME/gems"
fi
