#!/usr/bin/env bash
# Path export for Ruby Gems

if [[ ! `command -v gem` ]]; then
    return
fi

if [[ $PATH != *$HOME/gems/bin* ]]; then
    export PATH=$PATH:$HOME/gems/bin
fi

# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
