#!/usr/bin/bash
# Initial stuff. Gotta have em here at the start.
alias mine="cd $DOTFILE_ROOT"

# Important. Never delete.
alias please='sudo '

# Source aliases
for f in $DOTFILE_ROOT/bash_aliases/alias_functions/*; do
    . "$f"
done
